default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: webhotel_development 
  username: postgres
  password:   

test:
  <<: *default
  database: webhotel_test
  username: postgres
  password:

production:
  <<: *default
  database: webhotel_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>